$('.owl-carousel').owlCarousel({
    nav:true,
    margin:10,
    dots:false,
    padding:10,
    responsive:{
        0:{
            items:1
        },
        400:{
            items:3
        },
        1000:{
            items:5
        }
    }
})